language: objective-c
xcode_workspace: Tesseract-OCR-iOS.xcworkspace
xcode_sdk:
    - iphonesimulator7.0
    - iphonesimulator8.1 
xcode_scheme: 
    - Template Framework Project
    - TestsProject
after_success:
    ./scripts/coveralls.rb --extension m --extension mm --exclude-folder include

